### ISSUE TITLE
PR closed instead of merged

### ISSUE THREAD

**Issue by thomasmarshall** [futurelearn/squiddy#13]
This [PR](https://github.com/futurelearn/futurelearn/pull/7675) appears "closed" rather than "merged" even though the commits have been successfully rebased and merged into the `master` branch.

It looks like the force-push event happened, but the commit hashes listed in the PR haven't updated. I wonder if GitHub couldn't recognise that the commits had been merged, maybe because the branch was deleted _before_ GitHub had a chance to register the force-push event?

**Comment by elenatanasoiu** [comment]
This should be fixed by https://github.com/futurelearn/squiddy/pull/16

Closing for now. I'll re-open if it happens again.
